config/routes.rb
TrainDatabase::Application.routes.draw do
  get "dashboard/index"

  resources :train_locomotives

  resources :train_cars

  resources :owners

  resources :locomotive_types

  resources :car_types

  resources :decoders

  resources :makes

  resources :operators

  root 'dashboard#index'

end

app/controllers/car_types_controller.rb
class CarTypesController < ApplicationController
  before_action :set_car_type, only: [:show, :edit, :update, :destroy]

  # GET /car_types
  # GET /car_types.json
  def index
    @car_types = CarType.all
  end

  # GET /car_types/1
  # GET /car_types/1.json
  def show
  end

  # GET /car_types/new
  def new
    @car_type = CarType.new
  end

  # GET /car_types/1/edit
  def edit
  end

  # POST /car_types
  # POST /car_types.json
  def create
    @car_type = CarType.new(car_type_params)

    respond_to do |format|
      if @car_type.save
        format.html { redirect_to @car_type, notice: 'Car type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @car_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_types/1
  # PATCH/PUT /car_types/1.json
  def update
    respond_to do |format|
      if @car_type.update(car_type_params)
        format.html { redirect_to @car_type, notice: 'Car type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_types/1
  # DELETE /car_types/1.json
  def destroy
    @car_type.destroy
    respond_to do |format|
      format.html { redirect_to car_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_type
      @car_type = CarType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_type_params
      params.require(:car_type).permit(:name)
    end
end

app/helpers/car_types_helper.rb
module CarTypesHelper
end

app/views/car_types/_form.html.erb
<%= semantic_form_for @car_type do |form| %>
  <%= form.inputs do %>
    <%= form.input :name, :label => "Type navn" %>
  <% end %>
  <%= form.actions %>
<% end %>

app/views/car_types/edit.html.erb
<h1>Rediger vogntype</h1>

<%= render 'form' %>

<%= link_to 'Show', @car_type %> |
<%= link_to 'Back', car_types_path %>

app/views/car_types/index.html.erb
<h1>Vogntyper</h1>

<table>
  <thead>
    <tr>
      <th>Navn</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @car_types.each do |car_type| %>
      <tr>
        <td><%= car_type.name %></td>
        <td><%= link_to 'Vis', car_type %></td>
        <td><%= link_to 'Rediger', edit_car_type_path(car_type) %></td>
        <td><%= link_to 'Slet', car_type, method: :delete, data: { confirm: 'Er du sikker?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ny vogntype', new_car_type_path %>

app/views/car_types/new.html.erb
<h1>Ny vogntype</h1>

<%= render 'form' %>

<%= link_to 'Tilbage', car_types_path %>

app/views/car_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Navn:</strong>
  <%= @car_type.name %>
</p>

<%= link_to 'Rediger', edit_car_type_path(@car_type) %> |
<%= link_to 'Tilbage', car_types_path %>