config/routes.rb
TrainDatabase::Application.routes.draw do
  get "dashboard/index"

  resources :train_locomotives

  resources :train_cars

  resources :owners

  resources :locomotive_types

  resources :car_types

  resources :decoders

  resources :makes

  resources :operators

  root 'dashboard#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :train_cars
  has_many :train_locomotives
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @owner }
      else
        format.html { render action: 'new' }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= semantic_form_for @owner do |form| %>
  <%= form.inputs do %>
    <%= form.input :name, :label => "Navn" %>
  <% end %>
  <%= form.actions %>
<% end %>

app/views/owners/edit.html.erb
<h1>Rediger ejer</h1>

<%= render 'form' %>

<%= link_to 'Vis', @owner %> |
<%= link_to 'Tilbage', owners_path %>

app/views/owners/index.html.erb
<h1>Ejere</h1>

<table>
  <thead>
    <tr>
      <th>Navn</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= link_to 'Vis', owner %></td>
        <td><%= link_to 'Rediger', edit_owner_path(owner) %></td>
        <td><%= link_to 'Slet', owner, method: :delete, data: { confirm: 'Er du sikker?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ny ejer', new_owner_path %>

app/views/owners/new.html.erb
<h1>Ny ejer</h1>

<%= render 'form' %>

<%= link_to 'Tilbage', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Navn:</strong>
  <%= @owner.name %>
</p>

<%= link_to 'Rediger', edit_owner_path(@owner) %> |
<%= link_to 'Tilbage', owners_path %>