config/routes.rb
TrainDatabase::Application.routes.draw do
  get "dashboard/index"

  resources :train_locomotives

  resources :train_cars

  resources :owners

  resources :locomotive_types

  resources :car_types

  resources :decoders

  resources :makes

  resources :operators

  root 'dashboard#index'

end

app/models/decoder.rb
class Decoder < ActiveRecord::Base
  has_many :train_lociomotives
end

app/controllers/decoders_controller.rb
class DecodersController < ApplicationController
  before_action :set_decoder, only: [:show, :edit, :update, :destroy]

  # GET /decoders
  # GET /decoders.json
  def index
    @decoders = Decoder.all
  end

  # GET /decoders/1
  # GET /decoders/1.json
  def show
  end

  # GET /decoders/new
  def new
    @decoder = Decoder.new
  end

  # GET /decoders/1/edit
  def edit
  end

  # POST /decoders
  # POST /decoders.json
  def create
    @decoder = Decoder.new(decoder_params)

    respond_to do |format|
      if @decoder.save
        format.html { redirect_to @decoder, notice: 'Decoder was successfully created.' }
        format.json { render action: 'show', status: :created, location: @decoder }
      else
        format.html { render action: 'new' }
        format.json { render json: @decoder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decoders/1
  # PATCH/PUT /decoders/1.json
  def update
    respond_to do |format|
      if @decoder.update(decoder_params)
        format.html { redirect_to @decoder, notice: 'Decoder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @decoder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decoders/1
  # DELETE /decoders/1.json
  def destroy
    @decoder.destroy
    respond_to do |format|
      format.html { redirect_to decoders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_decoder
      @decoder = Decoder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def decoder_params
      params.require(:decoder).permit(:name)
    end
end

app/helpers/decoders_helper.rb
module DecodersHelper
end

app/views/decoders/_form.html.erb
<%= semantic_form_for @decoder do |form| %>
  <%= form.inputs do %>
    <%= form.input :name, :label => "Dekoder navn" %>
  <% end %>
  <%= form.actions %>
<% end %>

app/views/decoders/edit.html.erb
<h1>Rediger dekoder</h1>

<%= render 'form' %>

<%= link_to 'Vis', @decoder %> |
<%= link_to 'Tilbage', decoders_path %>

app/views/decoders/index.html.erb
<h1>Dekodere</h1>

<table>
  <thead>
    <tr>
      <th>Navn</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @decoders.each do |decoder| %>
      <tr>
        <td><%= decoder.name %></td>
        <td><%= link_to 'Vis', decoder %></td>
        <td><%= link_to 'Rediger', edit_decoder_path(decoder) %></td>
        <td><%= link_to 'Slet', decoder, method: :delete, data: { confirm: 'Er du sikker?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ny dekoder', new_decoder_path %>

app/views/decoders/new.html.erb
<h1>Ny dekoder</h1>

<%= render 'form' %>

<%= link_to 'Tilbage', decoders_path %>

app/views/decoders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Navn:</strong>
  <%= @decoder.name %>
</p>

<%= link_to 'Rediger', edit_decoder_path(@decoder) %> |
<%= link_to 'Tilbage', decoders_path %>